#!/usr/bin/env bash
# Rebuilds `home.img.gz` — the ext4 image `ext4/filesystem.test.ts` reads.
#
# Run this only when the fixture needs to change; the result is checked in so the
# tests are hermetic and need neither docker nor Linux.
#
#     ./build-fixture.sh
#
# The image is made the same way a real machine's persistent disk is made:
# `mkfs.ext4` on a RAW DEVICE with no partition table, matching
# `homeVolumeSection()` in `services/ProvisioningService.azure.ts`. If that
# command ever changes, change this one with it — a reader tested against a
# filesystem built differently from the one in production proves nothing.
#
# `-d` populates the image at creation, so this needs no mount and no
# privileged container.
set -euo pipefail

cd "$(dirname "$0")"

docker run --rm -v "$PWD:/out" debian:bookworm-slim bash -euo pipefail -c '
  apt-get update -qq && apt-get install -yqq e2fsprogs >/dev/null

  STAGE=/stage
  mkdir -p "$STAGE/cloudable/projects/deep/nested"
  cd "$STAGE/cloudable"

  echo "the file someone needs back after they leave" > notes.txt
  printf "key = value\nother = 2\n" > projects/config.ini
  printf "{\n  \"name\": \"api\"\n}\n" > projects/package.json
  echo "buried" > projects/deep/nested/treasure.txt

  # Refused by the reader as binary, still downloadable. The NUL must land in the
  # first 8000 bytes, which is all `looksBinary` inspects.
  printf "PNG\x00\x01\x02binary payload" > logo.png

  # Larger than the 1 MiB inline ceiling: read must refuse it as too_large while
  # download still works. Also spans enough blocks to exercise a real extent.
  # Deliberately repetitive rather than random — the test needs the SIZE, and
  # random bytes would put two incompressible megabytes into the repository.
  # `head` first in the pipeline, not `yes`: under `pipefail` a producer killed
  # by SIGPIPE fails the whole script.
  head -c 2097152 /dev/zero | tr "\0" "z" > big.bin

  # Exactly at the inline boundary, to catch an off-by-one in the cap.
  head -c 1048576 /dev/zero | tr "\0" "a" > exactly-1mib.txt

  # Fast symlink (target < 60 bytes, stored inline in i_block) and a slow one
  # (target >= 60 bytes, stored in a data block) — different code paths.
  ln -s notes.txt link-to-notes
  ln -s "./projects/deep/nested/a-very-long-target-path-that-will-not-fit-inside-the-inode-block/../treasure.txt" link-long

  # Empty file and empty directory: both have no data blocks at all.
  : > empty.txt
  mkdir -p empty-dir

  # More than FS_MAX_ENTRIES (10_000), so listing it truncates. Empty files, so
  # this costs inodes and dirent blocks but almost no data.
  mkdir -p many
  for i in $(seq 1 12000); do : > "many/f$i"; done

  # Unreadable-by-others on a live machine. There is no uid to enforce it against
  # here, which is the honest property the reader has to state rather than fake:
  # the mode is reported, not applied.
  echo "not actually secret to this reader" > private.txt
  chmod 600 private.txt

  chown -R 1000:1000 "$STAGE/cloudable"

  # -b 4096 because that is what mke2fs picks for a real machine volume; left to
  # itself it would choose 1024 for an image this small and the fixture would
  # stop resembling production. -N 16000 because the default one-inode-per-16KiB
  # would not cover 12k files on a volume this size.
  rm -f /out/home.img
  mkfs.ext4 -F -m 1 -b 4096 -L cloudable-home -N 16000 -d "$STAGE" /out/home.img 96M >/dev/null

  # What the tests assert against, captured from the real filesystem rather than
  # from our own reader, so the test cannot agree with a bug in it.
  {
    echo "# generated by build-fixture.sh — do not edit"
    debugfs -R "ls -l /cloudable" /out/home.img 2>/dev/null
  } > /out/expected-root.txt

  gzip -9 -f /out/home.img
  chmod 644 /out/home.img.gz /out/expected-root.txt
'

ls -l home.img.gz expected-root.txt
