import { index, integer, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { actorTypeEnum } from "../shared";

// ---------------------------------------------------------------------------
// APPEND-ONLY. Do not call .update() or .delete() against this table, ever,
// from anywhere outside this package's own tooling (e.g. a retention/expiry
// job). Events are the evidence trail the whole product is built on —
// no updates, no deletes, retention is expiry. The control plane derives
// audit state from this stream — mutating a row after the fact would
// falsify history.
//
// `type` values are a public interface: additive only, never
// renamed or removed. See `packages/events` for the catalogue and its
// snapshot test.
// ---------------------------------------------------------------------------
export const events = pgTable(
  "events",
  {
    // ULID, generated by the application at write time — deliberately NOT a
    // database default, so callers can assign the id before the row exists
    // (e.g. to correlate it with in-flight work) and so ids sort by time.
    id: text("id").primaryKey(),
    type: text("type").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
    recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
    orgId: uuid("org_id").notNull(),
    actorType: actorTypeEnum("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    machineId: uuid("machine_id"),
    correlationId: text("correlation_id").notNull(),
    schemaVersion: integer("schema_version").notNull(),
    payload: jsonb("payload").notNull(),
  },
  (table) => [index("events_org_type_occurred_idx").on(table.orgId, table.type, table.occurredAt)],
);
